// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api.proto

#include "api.pb.h"
#include "api.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* APIService_method_names[] = {
  "/APIService/GetAllMachines",
};

std::unique_ptr< APIService::Stub> APIService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< APIService::Stub> stub(new APIService::Stub(channel));
  return stub;
}

APIService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetAllMachines_(APIService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status APIService::Stub::GetAllMachines(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::MachineArrMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::MachineArrMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAllMachines_, context, request, response);
}

void APIService::Stub::experimental_async::GetAllMachines(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::MachineArrMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::MachineArrMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllMachines_, context, request, response, std::move(f));
}

void APIService::Stub::experimental_async::GetAllMachines(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::MachineArrMessage* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllMachines_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MachineArrMessage>* APIService::Stub::PrepareAsyncGetAllMachinesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::MachineArrMessage, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAllMachines_, context, request);
}

::grpc::ClientAsyncResponseReader< ::MachineArrMessage>* APIService::Stub::AsyncGetAllMachinesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllMachinesRaw(context, request, cq);
  result->StartCall();
  return result;
}

APIService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::google::protobuf::Empty, ::MachineArrMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::MachineArrMessage* resp) {
               return service->GetAllMachines(ctx, req, resp);
             }, this)));
}

APIService::Service::~Service() {
}

::grpc::Status APIService::Service::GetAllMachines(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::MachineArrMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


