// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

#include "echo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_echo_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_echo_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_echo_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_echo_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_echo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\necho.proto\032\rmessage.proto2\230\004\n\013EchoServ"
  "ice\022,\n\nEchoString\022\016.StringMessage\032\016.Stri"
  "ngMessage\022/\n\013EchoInteger\022\017.IntegerMessag"
  "e\032\017.IntegerMessage\022&\n\010EchoLong\022\014.LongMes"
  "sage\032\014.LongMessage\022)\n\tEchoFloat\022\r.FloatM"
  "essage\032\r.FloatMessage\022,\n\nEchoDouble\022\016.Do"
  "ubleMessage\032\016.DoubleMessage\022;\n\017EchoStrin"
  "gArray\022\023.StringArrayMessage\032\023.StringArra"
  "yMessage\022>\n\020EchoIntegerArray\022\024.IntegerAr"
  "rayMessage\032\024.IntegerArrayMessage\0225\n\rEcho"
  "LongArray\022\021.LongArrayMessage\032\021.LongArray"
  "Message\0228\n\016EchoFloatArray\022\022.FloatArrayMe"
  "ssage\032\022.FloatArrayMessage\022;\n\017EchoDoubleA"
  "rray\022\023.DoubleArrayMessage\032\023.DoubleArrayM"
  "essageb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_echo_2eproto_deps[1] = {
  &::descriptor_table_message_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_echo_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_echo_2eproto = {
  false, false, 574, descriptor_table_protodef_echo_2eproto, "echo.proto", 
  &descriptor_table_echo_2eproto_once, descriptor_table_echo_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_echo_2eproto::offsets,
  file_level_metadata_echo_2eproto, file_level_enum_descriptors_echo_2eproto, file_level_service_descriptors_echo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_echo_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_echo_2eproto);
  return descriptor_table_echo_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_echo_2eproto(&descriptor_table_echo_2eproto);

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
